version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
      POSTGRES_DB: basedatos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sparky

  redis:
    image: "redis:latest"
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sparky

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch_container
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - sparky

  mongodb:
    image: "mongo:latest"
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: usuario
      MONGO_INITDB_ROOT_PASSWORD: contraseña
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - sparky

  hdfs:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: hdfs_namenode
    environment:
      - CLUSTER_NAME=test
    volumes:
      - hdfs_data:/hadoop/dfs/name
    ports:
      - "9870:9870"
      - "9000:9000"
    networks:
      - sparky

  spark-master:
    image: sparky:latest
    container_name: spark_master
    environment:
      - SPARK_MODE=master
      - PYSPARK_PYTHON=python3.11
      - PYSPARK_DRIVER_PYTHON=python3.11
    ports:
      - "7077:7077"  # Puerto para el master de Spark
      - "8080:8080"  # Interfaz web de Spark
      - "8081:8081"  # Interfaz web del worker de Spark
    networks:
      - sparky

  spark-worker-1:
    image: sparky:latest
    container_name: spark_worker_1
    environment:
      - SPARK_MODE=worker
      - PYSPARK_PYTHON=python3.11
      - PYSPARK_DRIVER_PYTHON=python3.11
      - SPARK_MASTER_URL=spark://spark_master:7077
    networks:
      - sparky

  django-app:
    build: ./path_to_your_django_project
    container_name: django_container
    volumes:
      - ./path_to_your_django_project:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - sparky
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings.production
      - SECRET_KEY=your_secret_key_here
      - DATABASE_URL=postgres://usuario:contraseña@db:5432/basedatos

networks:
  sparky:

volumes:
  pgdata:
  redis_data:
  esdata:
  mongo_data:
  hdfs_data: